module.exports = {
	enableMessages: true,
    messageIncomingCall: "Incoming Call",
    messageProgress: "Ringing",
    messageStarted: "Call Started",
    messageHold: "Call placed on hold",
    messageResume: "Call removed from hold",
    messageEnded: "Call Ended",
    messageCall: "Performing NAT Tests",
    messageFailed: "Call Failed : {0}",
    messageConnected: "Connected",
    messageConnectionFailed: "Connection failed",
    messageUnregistered: "Unregistered",
    messageRegistered: "Registration successful",
    messageRegistrationNotFound: "Registration : Not Found",
    messageRegistrationWrongPassword: "Registration : Wrong Password",
    messageGetUserMedia: "Unable to Access Camera and/or Microphone",
    messageRegistering: "Registering...",
    messageUnregistering: "Unregistering...",
    messageConnecting: "Connecting to WRS..."
};